### ISSUE TITLE
BOPS 容器化部署

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-plugins-bdp#2]
BOPS各组件进行容器化部署改造，包括bops-web、zabbix-web、cms、change、monitor、zabbix-server、zabbix-proxy和数据库mariadb的镜像

**Comment by brankbao** [comment]
需要容器化的组件:
   1. mysql（他们用的是 mariadb10.1.9），将所有的sql source都打包到一个镜像里
   2. cms、change、ras、scheduer和moniotor打成一个镜像，里面放上启动4个组件的不同启动脚本，要启动哪个，到时就通过docker run启动命令
   3. eureka，自己做
   4. zabbix-server和对应的mysql
   5. zabbix-proxy和对应的mysql
   6. api-gateway
   7. uc
   8. nginx 网页容器化
