### ISSUE TITLE
新建BOPS适配器，主要功能是将WeCube的请求转换成BOPS系统能处理的请求

### ISSUE THREAD

**Issue by haixinhuang** [WeBankPartners/wecube-plugins-bdp#8]
在不修改WeCube调用插件接口逻辑和不修改BOPS系统接口的前提下，为了实现WeCube调用BOPS接口，初定方案是 新建BOPS适配器，主要功能是将WeCube的请求转换成BOPS系统能处理的请求。
本issue的需求就是新建BOPS适配器，主要功能是将WeCube的请求转换成BOPS系统能处理的请求。

**Comment by HoweChen** [comment]
Done
